//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workouts
    {
        public int WorkoutID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int TrainerID { get; set; }
        public int MaxParticipants { get; set; }
        public string Location { get; set; }
        public int BookingID { get; set; }
    
        public virtual Trainers Trainers { get; set; }
        public virtual WorkoutBookings WorkoutBookings { get; set; }
    }
}
